#!/bin/bash

sqlite3 0/paxolite.db 'select * from paxos order by log_seq' | md5sum
sqlite3 1/paxolite.db 'select * from paxos order by log_seq' | md5sum
sqlite3 2/paxolite.db 'select * from paxos order by log_seq' | md5sum
sqlite3 3/paxolite.db 'select * from paxos order by log_seq' | md5sum
sqlite3 4/paxolite.db 'select * from paxos order by log_seq' | md5sum
