#!/bin/bash

sqlite3 0/paxolite.db 'select * from paxos order by log_seq' > a
sqlite3 1/paxolite.db 'select * from paxos order by log_seq' > b
sqlite3 2/paxolite.db 'select * from paxos order by log_seq' > c
sqlite3 3/paxolite.db 'select * from paxos order by log_seq' > d
sqlite3 4/paxolite.db 'select * from paxos order by log_seq' > e
