#!/bin/bash

(cd 0 && while true; do python3 ~/magicray/paxolite/paxolite.py --port 5000; done) &
(cd 1 && while true; do python3 ~/magicray/paxolite/paxolite.py --port 5001; done) &
(cd 2 && while true; do python3 ~/magicray/paxolite/paxolite.py --port 5002; done) &
(cd 3 && while true; do python3 ~/magicray/paxolite/paxolite.py --port 5003; done) &
(cd 4 && while true; do python3 ~/magicray/paxolite/paxolite.py --port 5004; done) &
